### ISSUE TITLE
Alternative videos

### ISSUE THREAD

**Issue by stereobooster** [lucasviola/awesome-tech-videos#5]
I have a bit of different view on what types of video should be listed. I started to think of videos which I believe most influential, inspiring and powerful. And every video which I can think of was absent in your list, and not all of listed videos I would place in one row with videos I'm thinking of. So instead of pushing them all here I started new list https://github.com/stereobooster/cs-video. Maybe we can think of good way to join two list or separate responsibilities.

**Comment by lucasviola** [comment]
Well, feel welcome to contribute to videos you think should be in the list. Or if you want to rearrange the list in some sort of way. Just open a PR and I will be more than happy to read it carefully and take into account the way you think things shouldbe :)

But I did not understand why you had to open an Issue to state your opinion. People have different views on things, that is why  we create different project and come up with different solutions to the same problem, and that is what makes Open Source a great thing. So if you want to make your own list, I  totally encourage you to do that and I will leave this here so people can find it :)
