### ISSUE TITLE
Add Dev.Tube

### ISSUE THREAD

**Issue by sizovs** [lucasviola/awesome-tech-videos#8]
Hey @lucasviola 

We've launched [dev.tube](https://dev.tube) tech video hub and it has gained huge momentum in the tech community.

It would be great have it in your list. I didn't find a good section for it, though :) 

– Ed

**Comment by lucasviola** [comment]
You can open a PR directly to the project and add it if you want it :) Thanks for the suggestion! As this is an old issue and I do not know the status of the project I will close it.
